version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: 'monthly_book_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'mb_db_pass@2020'
      MYSQL_ROOT_PASSWORD: 'mb_db_pass@2020'
    volumes:
      - monthly_book_db_data:/var/lib/mysql
  web:
    build: .
    command: python manage.py runsslserver 0.0.0.0:8000
    volumes:
      - ./monthly_book/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  monthly_book_db_data: