# Generated by Django 3.1.3 on 2020-11-25 13:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('prodcut_desc', models.TextField()),
                ('product_qty', models.FloatField()),
                ('product_unit', models.CharField(max_length=16)),
                ('product_code', models.CharField(max_length=191, unique=True)),
                ('product_rate_per_unit', models.FloatField()),
                ('product_ccy', models.CharField(max_length=3)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2020, 11, 25, 17, 35, 6, 203714))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.TextField()),
                ('store_address', models.TextField()),
                ('store_type', models.CharField(max_length=32)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2020, 11, 25, 17, 35, 6, 203221))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_timestamp', models.DateTimeField(default=datetime.datetime(2020, 11, 25, 17, 35, 6, 204131))),
                ('txn_dop', models.DateField(default=datetime.date(2020, 11, 25))),
                ('txn_qty', models.FloatField()),
                ('txn_unit', models.CharField(max_length=16)),
                ('txn_amount', models.FloatField()),
                ('txn_ccy', models.CharField(max_length=3)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mbook.products')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mbook.stores')),
            ],
        ),
    ]
