# Generated by Django 3.1.3 on 2020-11-25 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 13, 37, 42, 822908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stores',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 13, 37, 42, 822426, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_dop',
            field=models.DateField(default=datetime.datetime(2020, 11, 25, 13, 37, 42, 823428, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 13, 37, 42, 823340, tzinfo=utc)),
        ),
    ]
