# Generated by Django 3.1.3 on 2020-11-25 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mbook', '0002_auto_20201125_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stores',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_dop',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
