# Generated by Django 3.1.3 on 2020-12-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbook', '0004_products_product_is_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='store_name',
            field=models.CharField(max_length=512),
        ),
    ]
