# Generated by Django 3.1.3 on 2020-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbook', '0007_auto_20201218_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_barcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
