# Generated by Django 3.1.3 on 2021-01-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbook', '0009_auto_20201219_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='txn_remarks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(default='0000000000000', max_length=191, null=True),
        ),
    ]
